### ISSUE TITLE
Problems I Encountered when using ModelPolicy

### ISSUE THREAD

**Issue by jedymatt** [painlesscode/breeze-multiauth#10]
The problem with multi auth using policy is that it does not work because it depends on `Auth::user()` instead of your intended guard like `Auth::guard('admin')->user()`.

For example:
```php
class DepartmentPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     *
     * @param \App\Models\Admin $admin
     * @return \Illuminate\Auth\Access\Response|bool
     */
    public function viewAny(Admin $admin)
    {
        return true;
    }

    // ...
}
```

Registering DepartmentPolicy in the Controller
```php
class DepartmentController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Department::class, 'department');
    }

    // ...
```

routes/admin.php
```php
Route::resource('/departments', DepartmentController::class);
```

If we try to visit <http://localhost:8000/admin/departments> we got `403 | THIS ACTION IS UNAUTHORIZED.` page despite the viewAny's true value. It is because the auth calls the default `web` guard instead of `admin`.

Here is the full detail in the [gist](https://gist.github.com/jedymatt/bcf21b7a82e011ef6ee09dcda863c04a) and how to approach this problem.

I suggest creating a middleware if it is possible. Thank you for your time to read.

**Comment by HazzazBinFaiz** [comment]
I tried to reproduce this error.

Actually laravel already does this for you.
If you use `auth:admin` middleware in any route, laravel checks the guard and use it as default.


[Reference](https://github.com/laravel/framework/blob/d1c3d4fb02df18a8b9b31c2ba6e4d76861f33d4b/src/Illuminate/Auth/Middleware/Authenticate.php#L64)

You just need to attach the middleware and everything should be ok.
```php
Route::resource('/departments', DepartmentController::class)->middleware('auth:admin');
```

**Comment by jedymatt** [comment]
Oh thank you for the information.
