### ISSUE TITLE
Where can I find specific route codes after creating a role?

### ISSUE THREAD

**Issue by Mainul12501** [painlesscode/breeze-multiauth#3]
I want to customize route codes. For example, when I create an admin role, route is created like this in web.php : 
`Route::multiauth('Admin', 'admin');`
here route('admin.login/register/etc') runs.

But I want to customize it. Where can I find route codes after creating an admin multiauth role?
like before:
`Route::post('/admin/login', ['ControllerName:: class, 'store'])->name('admin.login');`

**Comment by HazzazBinFaiz** [comment]
I've used a mixin on Route to register authentication routes for multiauth function.

You can find it [here](https://github.com/painlesscode/breeze-multiauth/blob/72fcb2fd1b244a11e6863905cc0a4b86dc886e4b/src/MultiAuthRouteMethods.php#L8)

 If you want to customize routes, you need to define all other necessary routes instead of using Route::multiauth()

**Comment by sam-hsbu** [comment]
Hello Dear. Can you explain to us how to use your class in order to make all the differents routes ?

Regards.

**Comment by sam-hsbu** [comment]
> I've used a mixin on Route to register authentication routes for multiauth function.
> 
> You can find it [here](https://github.com/painlesscode/breeze-multiauth/blob/72fcb2fd1b244a11e6863905cc0a4b86dc886e4b/src/MultiAuthRouteMethods.php#L8)
> 
> If you want to customize routes, you need to define all other necessary routes instead of using Route::multiauth()

Hi. Good job. Where do I have to put this file please ?

**Comment by HazzazBinFaiz** [comment]
> > I've used a mixin on Route to register authentication routes for multiauth function.
> > You can find it [here](https://github.com/painlesscode/breeze-multiauth/blob/72fcb2fd1b244a11e6863905cc0a4b86dc886e4b/src/MultiAuthRouteMethods.php#L8)
> > If you want to customize routes, you need to define all other necessary routes instead of using Route::multiauth()
> 
> Hi. Good job. Where do I have to put this file please ?

You can put all authentication route in different route file and include that file in web.php or you can define all the routes inside web.php.
Both will work.

If you want to customize it, you have to define all the routes defined in mixin.

```php
// assume that role name is admin
// remove Route::multiauth('Admin', 'admin'); and use your defined routes

Route::middleware(['auth:admin'])->name('admin.')->prefix(admin)->group(function() {
    Route::get('/', ["App\Http\Controllers\Admin\DashboardController", 'index']);
    Route::get('/dashboard', ["App\Http\Controllers\Admin\DashboardController", 'index'])->name('dashboard');

    /*---- rest of them ----*/
});
Route::middleware(['guest:admin'])->name('admin.')->prefix('admin')->group(function() {
    Route::get('/login', ["App\Http\Controllers\Admin\Auth\AuthenticatedSessionController", 'create'])
        ->name('login');

    /*--- rest of them ---*/
});

```
