### ISSUE TITLE
Implementing 2fa

### ISSUE THREAD

**Issue by egesarisac** [painlesscode/breeze-multiauth#4]
Hello, thank you for the package. I'm trying to implement 2fa login system. But i can't intercept the login process to ask to the user for 2fa codes. Can you help me? Thanks.

**Comment by HazzazBinFaiz** [comment]
You can use a middleware like laravel's build in password.confirm middleware to confirm users 2FA code

**Comment by mxts** [comment]
@HazzazBinFaiz 2FA also requires its own "registration" etc, is it on the roadmap of this package to support it?

**Comment by HazzazBinFaiz** [comment]
I've created this package to support laravel breeze.
So, 2FA is not in roadmap of this package.

**Comment by mxts** [comment]
@HazzazBinFaiz I see, ok. Btw, do you take on projects? Possible to contact you privately? Thank you.

**Comment by HazzazBinFaiz** [comment]
I am not working on any project this month for academic examination.
