### ISSUE TITLE
Delete created auth system

### ISSUE THREAD

**Issue by ArtMin96** [painlesscode/breeze-multiauth#5]
Can we delete the created authentication system?

**Comment by HazzazBinFaiz** [comment]
Yes, But some code can't be reverted which is already replaced by the package. like webpack.mix.js

Assuming you want to delete authentication for role **Admin**
To clean created authentication system, you need to delete
 
 - Http/Controllers/Admin - (directory)
 - Http/Requests/Admin - (directory)
 - views/admin - (directory)
 - tests/Feature/Admin - (directory)
 - App/Models/Admin.php - (file)
 - database/factories/AdminFactory.php - (file)
 - database/migrations/xxxx_xx_xx_000000_create_admins_table.php - (file)
 
 and also,
 - remove **Route::multiauth('Admin', 'admin');** from routes/web.php
 - remove admins guard, provider and passwords from config/auth.php
 - remove admin guard checking block of code from app/Http/Middleware/Authenticate.php
 - remove admin guard checking block of code from Http/Middleware/RedirectIfAuthenticated.php
