### ISSUE TITLE
Problem with replacing code in files

### ISSUE THREAD

**Issue by ArtMin96** [painlesscode/breeze-multiauth#7]
There is a big problem with changing files. It completely removes the previous code. For example, the package removed turbolink from webpack.mix.js and cleared the code from tailwind.config.js. This is a very serious issue in my opinion.

**Comment by HazzazBinFaiz** [comment]
It works in the same way like laravel breeze works.
Breeze replace the existing webpack.mix.js and tailwind.config.js

**Comment by HazzazBinFaiz** [comment]
There is an option **--asset**

If this option is not provided during authentication installation this package won't touch those files,
- package.json
- tailwind.config.js
- webpack.mix.js
- resources/css/app.css
- resources/js/app.js

**Comment by ArtMin96** [comment]
Thank you so much!
