### ISSUE TITLE
Attribute [multiauth] does not exist

### ISSUE THREAD

**Issue by axahito** [painlesscode/breeze-multiauth#8]
good day, first of all i'd like to thank you for the package, been using it multiple times now.

this particular issue shows up when i tried to deploy the app to heroku. i've never get this error when i deployed the app manually on a VM, it didn't even show up during `composer install` or `composer update`. i figured it has something to do with the `multiauth` method used in the route?

so i was wondering if you know of a way to handle this? i couldn't find where the `multiauth` method is registered, but it works fine aside from this particular issue.

heroku build log  :
`
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/php
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
       - php (8.0.10)
       - ext-gd (bundled with php)
       - ext-mbstring (bundled with php)
       - composer (2.1.6)
       - apache (2.4.48)
       - nginx (1.20.1)
-----> Installing dependencies...
       Composer version 2.1.6 2021-08-19 17:11:08
       Installing dependencies from lock file
       Verifying lock file contents can be installed on current platform.
       Package operations: 84 installs, 0 updates, 0 removals
         - Installing doctrine/inflector (2.0.3): Extracting archive
         - Installing doctrine/lexer (1.2.1): Extracting archive
         - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
         - Installing webmozart/assert (1.10.0): Extracting archive
         - Installing dragonmantank/cron-expression (v3.1.0): Extracting archive
         - Installing voku/portable-ascii (1.5.6): Extracting archive
         - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
         - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
         - Installing phpoption/phpoption (1.8.0): Extracting archive
         - Installing graham-campbell/result-type (v1.0.2): Extracting archive
         - Installing vlucas/phpdotenv (v5.3.0): Extracting archive
         - Installing symfony/css-selector (v5.3.4): Extracting archive
         - Installing tijsverkoyen/css-to-inline-styles (2.2.3): Extracting archive
         - Installing symfony/var-dumper (v5.3.7): Extracting archive
         - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
         - Installing symfony/routing (v5.3.7): Extracting archive
         - Installing symfony/process (v5.3.7): Extracting archive
         - Installing symfony/polyfill-php72 (v1.23.0): Extracting archive
         - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
         - Installing symfony/polyfill-intl-idn (v1.23.0): Extracting archive
         - Installing symfony/mime (v5.3.7): Extracting archive
         - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
         - Installing symfony/http-foundation (v5.3.7): Extracting archive
         - Installing symfony/http-client-contracts (v2.4.0): Extracting archive
         - Installing psr/event-dispatcher (1.0.0): Extracting archive
         - Installing symfony/event-dispatcher-contracts (v2.4.0): Extracting archive
         - Installing symfony/event-dispatcher (v5.3.7): Extracting archive
         - Installing psr/log (1.1.4): Extracting archive
         - Installing symfony/error-handler (v5.3.7): Extracting archive
         - Installing symfony/http-kernel (v5.3.7): Extracting archive
         - Installing symfony/finder (v5.3.7): Extracting archive
         - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive
         - Installing symfony/string (v5.3.7): Extracting archive
         - Installing psr/container (1.1.1): Extracting archive
         - Installing symfony/service-contracts (v2.4.0): Extracting archive
         - Installing symfony/console (v5.3.7): Extracting archive
         - Installing symfony/polyfill-iconv (v1.23.0): Extracting archive
         - Installing egulias/email-validator (2.1.25): Extracting archive
         - Installing swiftmailer/swiftmailer (v6.2.7): Extracting archive
         - Installing symfony/polyfill-php81 (v1.23.0): Extracting archive
         - Installing ramsey/collection (1.2.1): Extracting archive
         - Installing brick/math (0.9.3): Extracting archive
         - Installing ramsey/uuid (4.2.1): Extracting archive
         - Installing psr/simple-cache (1.0.1): Extracting archive
         - Installing opis/closure (3.6.2): Extracting archive
         - Installing symfony/translation-contracts (v2.4.0): Extracting archive
         - Installing symfony/translation (v5.3.7): Extracting archive
         - Installing nesbot/carbon (2.52.0): Extracting archive
         - Installing monolog/monolog (2.3.2): Extracting archive
         - Installing league/mime-type-detection (1.7.0): Extracting archive
         - Installing league/flysystem (1.1.5): Extracting archive
         - Installing nette/utils (v3.2.3): Extracting archive
         - Installing nette/schema (v1.2.1): Extracting archive
         - Installing dflydev/dot-access-data (v3.0.1): Extracting archive
         - Installing league/config (v1.1.1): Extracting archive
         - Installing league/commonmark (2.0.2): Extracting archive
         - Installing laravel/framework (v8.58.0): Extracting archive
         - Installing fideloper/proxy (4.4.1): Extracting archive
         - Installing asm89/stack-cors (v2.0.3): Extracting archive
         - Installing fruitcake/laravel-cors (v2.0.4): Extracting archive
         - Installing psr/http-message (1.0.1): Extracting archive
         - Installing psr/http-client (1.0.1): Extracting archive
         - Installing ralouphie/getallheaders (3.0.3): Extracting archive
         - Installing psr/http-factory (1.0.1): Extracting archive
         - Installing guzzlehttp/psr7 (2.0.0): Extracting archive
         - Installing guzzlehttp/promises (1.4.1): Extracting archive
         - Installing guzzlehttp/guzzle (7.3.0): Extracting archive
         - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
         - Installing laravel/sanctum (v2.11.2): Extracting archive
         - Installing nikic/php-parser (v4.12.0): Extracting archive
         - Installing psy/psysh (v0.10.8): Extracting archive
         - Installing laravel/tinker (v2.6.1): Extracting archive
         - Installing markbaker/matrix (2.1.3): Extracting archive
         - Installing markbaker/complex (2.0.3): Extracting archive
         - Installing myclabs/php-enum (1.8.3): Extracting archive
         - Installing maennchen/zipstream-php (2.1.0): Extracting archive
         - Installing ezyang/htmlpurifier (v4.13.0): Extracting archive
         - Installing phpoffice/phpspreadsheet (1.18.0): Extracting archive
         - Installing maatwebsite/excel (3.1.33): Extracting archive
         - Installing facade/ignition-contracts (1.0.2): Extracting archive
         - Installing qirolab/laravel-themer (1.5.0): Extracting archive
         - Installing mockery/mockery (1.4.3): Extracting archive
         - Installing spatie/laravel-package-tools (1.9.0): Extracting archive
         - Installing spatie/laravel-multitenancy (2.1.1): Extracting archive
       Generating optimized autoload files
       > Illuminate\Foundation\ComposerScripts::postAutoloadDump
       > @php artisan package:discover --ansi
       
       In RouteRegistrar.php line 93:
                                                
         Attribute [multiauth] does not exist.  
                                                
       
       Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
 !     WARNING: A post-autoload-dump script terminated with an error
 !     ERROR: Dependency installation failed!
 !     
 !     The 'composer install' process failed with an error. The cause
 !     may be the download or installation of packages, or a pre- or
 !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
 !     in your 'composer.json'.
 !     
 !     Typical error cases are out-of-date or missing parts of code,
 !     timeouts when making external connections, or memory limits.
 !     
 !     Check the above error output closely to determine the cause of
 !     the problem, ensure the code you're pushing is functioning
 !     properly, and that all local changes are committed correctly.
 !     
 !     For more information on builds for PHP on Heroku, refer to
 !     https://devcenter.heroku.com/articles/php-support
 !     
 !     REMINDER: the following warnings were emitted during the build;
 !     check the details above, as they may be related to this error:
 !     - A post-autoload-dump script terminated with an error
 !     Push rejected, failed to compile PHP app.
 !     Push failed
`

expected result : app deployed successfully.

output : Attribute [multiauth] does not exist

thanks in advance

update :

i've tried putting `Painless\BreezeMultiAuth\BreezeMultiAuthServiceProvider::class` in `app.php` but heroku deploy returns the class not found.

**Comment by HazzazBinFaiz** [comment]
As I can see in the heroku build log, this package is not being installed because it is installed as a dev-dependency.

It's my mistake, I've used `--dev` in installation command but this package uses a mixin to register routes and that mixin is required for proper route registration.

Quick fix will be just move this package from "require-dev" to "require" and run `composer install`

I am planning to remove complete dependency and use separate route file for next major version release.

Thanks to point out this issue.

**Comment by axahito** [comment]
ah yes, it worked fine now, thank you very much for the response
